Feature branch
sumon0002001/enumerable_methods pull request #1
Opened 2020-10-21 20:33 UTC by sumon0002001

****Advanced Building Blocks - Enumerable's****
-Basic Ruby is used to build advanced building blocks.
-Create our methods and run it in IRB to test them
-Add new methods onto the existing Enumerable module.
-Create #my_each
-Create #my_each_with_index
-Create #my_select
-Create #my_all?
-Create #my_any?
-Create #my_none?
-Create #my_count
-Create #my_map
-Create #my_inject

2020-10-21 23:41 UTC, blackpintz requested changes
# Status: Changes Required

### Hello team,

**Great job on your project. However, there are required changes below.**

### Mandatory

1). **There are unsolved rubocop offenses.**

![rubocop](https://user-images.githubusercontent.com/38922385/96792626-6eb8e300-1403-11eb-864e-1b3cb11f6d35.png)

2). **Disable `Style/CaseEquality` cop. ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/style_case_equality.png) from pathwright).**

3). **Provide a descriptive title for your pull request.**

4). **Check more comments below.**

## Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

2020-10-21 23:41 UTC, ghost commented on enumerable_methods.rb
> +  end
1). `my_each` method should iterate over a range of values and hash values.
```

# range values
(0..5).each {|x| print x, " -- " }   #=> 0 -- 1 -- 2 -- 3 -- 4 -- 5 --
(0..5).my_each {|x| print x, " -- " }  #=> `my_each': undefined method `[]' for 0..5:Range (NoMethodError)

# hash values
h = {foo: 0, bar: 1, baz: 2}

print h.each {|key, value| print "#{key}: #{value}"}  #=> foo: 0bar: 1baz: 2

print h.my_each {|key, value| print "#{key}: #{value}"} #=> : : :
```
2).` my_each` method should return enumerator if no block is given

```
print [1,2,3,4].each  #=> #<Enumerator:0x000055d510570c98>

print [1,2,3,4].my_each  #=>`my_each': no block given (yield) (LocalJumpError)
```

2020-10-21 23:41 UTC, ghost commented on enumerable_methods.rb
> +  end
Apply the same changes illustrated in the `my_each` method to the `my_each_with_index`. They include:

- iterations over range and hash values.

- Returning an enumerator when no block is given.

2020-10-21 23:41 UTC, ghost commented on enumerable_methods.rb
> +  end
`my_select` method should iterate over a range of values and return an enumerator when no block is given. 
```
# range

print (0..5).select { |num|  num.even?  }   #=> [0, 2, 4]
print (0..5).my_select { |num|  num.even?  }  #=> `my_each': undefined method `[]' for 0..5:Range (NoMethodError)

# when no block is given

print [1,2,3,4].select  #=> #<Enumerator:0x000055f4ea1488b0>
print [1,2,3,4].my_select  #=> `block in my_select': no block given (yield) (LocalJumpError)
```

2020-10-21 23:41 UTC, ghost commented on enumerable_methods.rb
> +  end
`my_all?` should iterate over a range of values.

```
puts (0..5).all?(Integer) #=> true
puts (0..5).my_all?(Integer)   #=> undefined method `[]' for 0..5:Range (NoMethodError)
```

2020-10-21 23:41 UTC, ghost commented on enumerable_methods.rb
> +  end
`my_any?` method should iterate over a range of values.

2020-10-21 23:41 UTC, blackpintz commented on enumerable_methods.rb
> +  end
The following tests for `my_none? `method are failing.
```

%w{ant bear cat}.my_none? { |word| word.length == 5 } 
%w{ant bear cat}.my_none?(/d/) 
[1, 3.14, 42].my_none?(Float) 
[nil, false, true].my_none?
(0..4).my_none?   
```

2020-10-21 23:41 UTC, blackpintz commented on enumerable_methods.rb
> +  end
The following test for the `my_count?` method is failing.

 `(0..5).my_count(2) `

2020-10-21 23:41 UTC, blackpintz commented on enumerable_methods.rb
> +  end
The following tests for  `my_map?` method are failing.

```
(1..4).my_map { |i| i*i }
(1..4).my_map { "cat"  }
```

2020-10-21 23:41 UTC, blackpintz commented on enumerable_methods.rb
> +  end
The following tests for `my_inject` method are failing.
```

(5..10).my_inject { |sum, n| sum + n }
(1..5).my_inject(:*) 
[1,2,3,4,5].my_inject(:*)
[1,2,3,4,5].my_inject(2, :*)
(1..5).my_inject(2, :*)
[5,6,7,8,9,10].my_inject(1) { |product, n| product * n }
(5..10).my_inject(1) { |product, n| product * n }
```

2020-10-21 23:41 UTC, blackpintz commented on enumerable_methods.rb
> +end
`multiply_els` is returning undefined.
`print multiply_els([2,4,5])  #=> undefined method `multiply_els' for main:Object (NoMethodError)`

2020-10-22 13:52 UTC, maelfosso requested changes
# Changes required 🔴 

Hello,

Thank you for implementing the suggested changes
However there are some missings requirements

1- There are linters'errors. Kindly fix them

2- There an error in your `enumerable_methods.rb` file.
```rb
$ ruby -wc enumerable_methods.rb 
enumerable_methods.rb:69: warning: mismatched indentations at 'end' with 'else' at 66
enumerable_methods.rb:60: warning: statement not reached
enumerable_methods.rb:71: warning: mismatched indentations at 'end' with 'if' at 57
enumerable_methods.rb:83: warning: mismatched indentations at 'elsif' with 'if' at 80
enumerable_methods.rb:85: warning: mismatched indentations at 'else' with 'if' at 80
enumerable_methods.rb:87: warning: mismatched indentations at 'end' with 'else' at 85
enumerable_methods.rb:89: warning: mismatched indentations at 'end' with 'def' at 78
enumerable_methods.rb:112: warning: mismatched indentations at 'end' with 'else' at 110
enumerable_methods.rb:114: warning: mismatched indentations at 'end' with 'def' at 103
enumerable_methods.rb:115: warning: mismatched indentations at 'end' with 'def' at 56
enumerable_methods.rb:119: warning: mismatched indentations at 'end' with 'def' at 117
enumerable_methods.rb:119: syntax error, unexpected end-of-input, expecting `end'
```
Fix them, please

3- There are some bugs. Kindly read the comments left below to know more about those errors.

Once fix, submit a new code review request, please.

Mael FOSSO

2020-10-22 13:52 UTC, maelfosso commented on enumerable_methods.rb
> +  end
```rb
2.6.5 :013 > array
 => [5, 2, 3, 7, 3, 5, 8, 3, 0, 7, 6, 7, 2, 1, 3, 7, 1, 1, 6, 5, 4, 0, 2, 7, 8, 4, 4, 4, 7, 3, 7, 8, 8, 1, 5, 1, 2, 8, 1, 8, 3, 5, 6, 3, 8, 3, 7, 7, 1, 5, 8, 0, 6, 0, 5, 8, 8, 1, 1, 7, 4, 1, 7, 6, 0, 1, 5, 2, 7, 1, 0, 6, 1, 7, 4, 8, 2, 2, 6, 6, 3, 2, 4, 6, 1, 4, 2, 4, 0, 3, 0, 4, 2, 0, 4, 4, 2, 4, 8, 8] 
2.6.5 :014 > array.my_each_with_index { |num| num + 1 }
Traceback (most recent call last):
        2: from (irb#1):14
        1: from enumerable_methods.rb:23:in `my_each_with_index'
NoMethodError (undefined method `class=' for #<Array:0x0000000001e1a0b8>)
Did you mean?  class
2.6.5 :015 > array.each_with_index { |num| num + 1 }
 => [5, 2, 3, 7, 3, 5, 8, 3, 0, 7, 6, 7, 2, 1, 3, 7, 1, 1, 6, 5, 4, 0, 2, 7, 8, 4, 4, 4, 7, 3, 7, 8, 8, 1, 5, 1, 2, 8, 1, 8, 3, 5, 6, 3, 8, 3, 7, 7, 1, 5, 8, 0, 6, 0, 5, 8, 8, 1, 1, 7, 4, 1, 7, 6, 0, 1, 5, 2, 7, 1, 0, 6, 1, 7, 4, 8, 2, 2, 6, 6, 3, 2, 4, 6, 1, 4, 2, 4, 0, 3, 0, 4, 2, 0, 4, 4, 2, 4, 8, 8] 
2.6.5 :016 > 
```

2020-10-22 13:52 UTC, maelfosso commented on enumerable_methods.rb
> +  end
```rb
2.6.5 :026 > my_each_with_index_output = ''
2.6.5 :027 > block = proc { |num, idx| my_each_with_index_output += "Num: #{num}, idx: #{idx}\n" }
2.6.5 :028 > hash.each_with_index(&block)
 => {:a=>1, :b=>2, :c=>3, :d=>4, :e=>5} 
2.6.5 :029 > each_with_index_output = my_each_with_index_output.dup
2.6.5 :030 > my_each_with_index_output = ''
2.6.5 :031 > hash.my_each_with_index(&block)
Traceback (most recent call last):
        2: from (irb#1):31
        1: from enumerable_methods.rb:23:in `my_each_with_index'
NoMethodError (undefined method `class=' for {:a=>1, :b=>2, :c=>3, :d=>4, :e=>5}:Hash)
Did you mean?  class
2.6.5 :032 >
```

2020-10-22 13:52 UTC, maelfosso commented on enumerable_methods.rb
> +  end
```rb
2.6.5 :034 > words = %w[dog door rod blade]
2.6.5 :035 > words.my_all?(/d/)
Traceback (most recent call last):
        2: from (irb#1):35
        1: from enumerable_methods.rb:49:in `my_all?'
NoMethodError (undefined method `nil' for /d/:Regexp)
Did you mean?  nil?
2.6.5 :036 > words.all?(/d/)
 => true 
2.6.5 :037 > words.my_all?(/z/)
Traceback (most recent call last):
        2: from (irb#1):37
        1: from enumerable_methods.rb:49:in `my_all?'
NoMethodError (undefined method `nil' for /z/:Regexp)
Did you mean?  nil?
2.6.5 :038 > words.all?(/z/)
 => false 
2.6.5 :039 >
```

2020-10-22 13:52 UTC, maelfosso commented on enumerable_methods.rb
> +  end
```rb
2.6.5 :041 > array
 => [5, 2, 3, 7, 3, 5, 8, 3, 0, 7, 6, 7, 2, 1, 3, 7, 1, 1, 6, 5, 4, 0, 2, 7, 8, 4, 4, 4, 7, 3, 7, 8, 8, 1, 5, 1, 2, 8, 1, 8, 3, 5, 6, 3, 8, 3, 7, 7, 1, 5, 8, 0, 6, 0, 5, 8, 8, 1, 1, 7, 4, 1, 7, 6, 0, 1, 5, 2, 7, 1, 0, 6, 1, 7, 4, 8, 2, 2, 6, 6, 3, 2, 4, 6, 1, 4, 2, 4, 0, 3, 0, 4, 2, 0, 4, 4, 2, 4, 8, 8] 
2.6.5 :042 > array.all?(3)
 => false 
2.6.5 :043 > array.my_all?(3)
Traceback (most recent call last):
        2: from (irb#1):43
        1: from enumerable_methods.rb:49:in `my_all?'
NoMethodError (undefined method `nil' for 3:Integer)
Did you mean?  nil?
2.6.5 :044 > 
```

2020-10-22 13:52 UTC, maelfosso commented on enumerable_methods.rb
> +  end
```rb
2.6.5 :046 > true_array = [nil, false, true, []]
2.6.5 :047 > true_array.any?
 => true 
2.6.5 :048 > true_array.my_any?
 => :my_inject 
2.6.5 :049 > 
```

2020-10-22 13:52 UTC, maelfosso commented on enumerable_methods.rb
> +  end
```rb
2.6.5 :051 > false_array = [nil, false, nil, false]
2.6.5 :052 > false_array.any?
 => false 
2.6.5 :053 > false_array.my_any?
 => :my_inject 
2.6.5 :054 > 
```

2020-10-22 13:52 UTC, maelfosso commented on enumerable_methods.rb
> +  end
```rb
2.6.5 :056 > array
 => [5, 2, 3, 7, 3, 5, 8, 3, 0, 7, 6, 7, 2, 1, 3, 7, 1, 1, 6, 5, 4, 0, 2, 7, 8, 4, 4, 4, 7, 3, 7, 8, 8, 1, 5, 1, 2, 8, 1, 8, 3, 5, 6, 3, 8, 3, 7, 7, 1, 5, 8, 0, 6, 0, 5, 8, 8, 1, 1, 7, 4, 1, 7, 6, 0, 1, 5, 2, 7, 1, 0, 6, 1, 7, 4, 8, 2, 2, 6, 6, 3, 2, 4, 6, 1, 4, 2, 4, 0, 3, 0, 4, 2, 0, 4, 4, 2, 4, 8, 8] 
2.6.5 :057 > array.my_any?(Numeric)
 => :my_inject 
2.6.5 :058 > array.any?(Numeric)
 => true 
2.6.5 :059 > 
```

2020-10-22 13:52 UTC, maelfosso commented on enumerable_methods.rb
> +  end
```rb
2.6.5 :061 > false_array = [nil, false, nil, false]
2.6.5 :062 > false_array.my_none?
 => false 
2.6.5 :063 > false_array.none?
 => true 
2.6.5 :064 >
```

2020-10-22 13:52 UTC, maelfosso commented on enumerable_methods.rb
> +  end
```rb
2.6.5 :066 > words
 => ["dog", "door", "rod", "blade"] 
2.6.5 :067 > words.my_none?(/z/)
 => false 
2.6.5 :068 > words.none?(/z/)
 => true 
2.6.5 :069 > 
```

2020-10-22 13:52 UTC, maelfosso commented on enumerable_methods.rb
> +      end
```rb
2.6.5 :074 > range = Range.new(5, 50)
2.6.5 :075 > range.my_inject(4) { |prod, n| prod * n }
Traceback (most recent call last):
        2: from (irb#1):75
        1: from enumerable_methods.rb:104:in `my_inject'
NoMethodError (undefined method `is_a' for 4:Integer)
Did you mean?  is_a?
2.6.5 :076 > range.inject(4) { |prod, n| prod * n }
 => 5069015533618896340602101361010794807396273594826752000000000000 
2.6.5 :077 > 
```

2020-10-22 13:52 UTC, maelfosso commented on enumerable_methods.rb
> +      end
```rb
2.6.5 :078 > array
 => [5, 2, 3, 7, 3, 5, 8, 3, 0, 7, 6, 7, 2, 1, 3, 7, 1, 1, 6, 5, 4, 0, 2, 7, 8, 4, 4, 4, 7, 3, 7, 8, 8, 1, 5, 1, 2, 8, 1, 8, 3, 5, 6, 3, 8, 3, 7, 7, 1, 5, 8, 0, 6, 0, 5, 8, 8, 1, 1, 7, 4, 1, 7, 6, 0, 1, 5, 2, 7, 1, 0, 6, 1, 7, 4, 8, 2, 2, 6, 6, 3, 2, 4, 6, 1, 4, 2, 4, 0, 3, 0, 4, 2, 0, 4, 4, 2, 4, 8, 8] 
2.6.5 :079 > array.my_inject(:+)
Traceback (most recent call last):
        2: from (irb#1):79
        1: from enumerable_methods.rb:108:in `my_inject'
NameError (undefined local variable or method `block_given' for #<Array:0x0000000001e1a0b8>)
Did you mean?  block_given?
2.6.5 :080 > array.inject(:+)
 => 407 
2.6.5 :081 > 
```

2020-10-22 13:52 UTC, maelfosso commented on enumerable_methods.rb
> +      end
```rb
2.6.5 :081 > array
 => [5, 2, 3, 7, 3, 5, 8, 3, 0, 7, 6, 7, 2, 1, 3, 7, 1, 1, 6, 5, 4, 0, 2, 7, 8, 4, 4, 4, 7, 3, 7, 8, 8, 1, 5, 1, 2, 8, 1, 8, 3, 5, 6, 3, 8, 3, 7, 7, 1, 5, 8, 0, 6, 0, 5, 8, 8, 1, 1, 7, 4, 1, 7, 6, 0, 1, 5, 2, 7, 1, 0, 6, 1, 7, 4, 8, 2, 2, 6, 6, 3, 2, 4, 6, 1, 4, 2, 4, 0, 3, 0, 4, 2, 0, 4, 4, 2, 4, 8, 8] 
2.6.5 :082 > array.my_inject(20, :*)
Traceback (most recent call last):
        2: from (irb#1):82
        1: from enumerable_methods.rb:108:in `my_inject'
NameError (undefined local variable or method `block_given' for #<Array:0x0000000001e1a0b8>)
Did you mean?  block_given?
2.6.5 :083 > array.inject(20, :*)
 => 0 
2.6.5 :084 >
```

2020-10-22 13:52 UTC, maelfosso commented on enumerable_methods.rb
> +      end
```rb
2.6.5 :086 > range
 => 5..50 
2.6.5 :087 > range.my_inject(:*)
Traceback (most recent call last):
        2: from (irb#1):87
        1: from enumerable_methods.rb:108:in `my_inject'
NameError (undefined local variable or method `block_given' for 5..50:Range)
Did you mean?  block_given?
2.6.5 :088 > range.inject(:*)
 => 1267253883404724085150525340252698701849068398706688000000000000 
2.6.5 :089 > range.my_inject(20, :*)
Traceback (most recent call last):
        2: from (irb#1):89
        1: from enumerable_methods.rb:108:in `my_inject'
NameError (undefined local variable or method `block_given' for 5..50:Range)
Did you mean?  block_given?
2.6.5 :090 > range.inject(20, :*)
 => 25345077668094481703010506805053974036981367974133760000000000000 
2.6.5 :091 > 
```

2020-10-22 17:59 UTC, maelfosso requested changes
# Changes required 🔴 

Hello,

Thank you for implementing the suggested changes.
However, there are still bugs
Read the comments below to know more about the bug

Once fixing the bugs, submit a new code review request

Thanks
Mael FOSSO

2020-10-22 17:59 UTC, maelfosso commented on enumerable_methods.rb
> +  end
```rb
2.6.5 :014 > array
 => [2, 8, 0, 8, 1, 3, 2, 3, 2, 1, 5, 7, 0, 8, 4, 3, 7, 7, 3, 7, 5, 8, 2, 2, 6, 8, 0, 7, 7, 2, 5, 6, 7, 7, 5, 2, 3, 6, 2, 4, 8, 0, 5, 4, 0, 3, 3, 8, 5, 5, 5, 6, 0, 8, 4, 1, 5, 7, 1, 2, 7, 1, 3, 6, 4, 5, 3, 2, 7, 0, 5, 4, 1, 6, 1, 3, 2, 0, 7, 4, 2, 1, 8, 0, 3, 5, 6, 4, 5, 5, 3, 3, 4, 5, 4, 4, 7, 3, 5, 3] 
2.6.5 :015 > array.my_each_with_index { |num| num + 1 }
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):15
        1: from enumerable_methods.rb:23:in `my_each_with_index'
NameError (undefined local variable or method `var' for #<Array:0x0000000002838d60>)
2.6.5 :016 > array.each_with_index { |num| num + 1 }
 => [2, 8, 0, 8, 1, 3, 2, 3, 2, 1, 5, 7, 0, 8, 4, 3, 7, 7, 3, 7, 5, 8, 2, 2, 6, 8, 0, 7, 7, 2, 5, 6, 7, 7, 5, 2, 3, 6, 2, 4, 8, 0, 5, 4, 0, 3, 3, 8, 5, 5, 5, 6, 0, 8, 4, 1, 5, 7, 1, 2, 7, 1, 3, 6, 4, 5, 3, 2, 7, 0, 5, 4, 1, 6, 1, 3, 2, 0, 7, 4, 2, 1, 8, 0, 3, 5, 6, 4, 5, 5, 3, 3, 4, 5, 4, 4, 7, 3, 5, 3] 
2.6.5 :017 > 
```

2020-10-22 17:59 UTC, maelfosso commented on enumerable_methods.rb
> +      yield(var[i], i)
Where does that `var` come from?

2020-10-22 17:59 UTC, maelfosso commented on enumerable_methods.rb
> +  end
```rb
2.6.5 :019 > words = %w[dog door rod blade]
2.6.5 :020 > words.all?(/d/)
 => true 
2.6.5 :021 > words.my_all?(/d/)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):21
        1: from enumerable_methods.rb:46:in `my_all?'
NoMethodError (undefined method `nil' for /d/:Regexp)
Did you mean?  nil?
2.6.5 :022 > 
```

2020-10-22 17:59 UTC, maelfosso commented on enumerable_methods.rb
> +    elsif argument.class && !argument.nil == Regexp
It's `nil?` not `nil`

2020-10-22 17:59 UTC, maelfosso commented on enumerable_methods.rb
> +  end
```rb
2.6.5 :027 > array
 => [2, 8, 0, 8, 1, 3, 2, 3, 2, 1, 5, 7, 0, 8, 4, 3, 7, 7, 3, 7, 5, 8, 2, 2, 6, 8, 0, 7, 7, 2, 5, 6, 7, 7, 5, 2, 3, 6, 2, 4, 8, 0, 5, 4, 0, 3, 3, 8, 5, 5, 5, 6, 0, 8, 4, 1, 5, 7, 1, 2, 7, 1, 3, 6, 4, 5, 3, 2, 7, 0, 5, 4, 1, 6, 1, 3, 2, 0, 7, 4, 2, 1, 8, 0, 3, 5, 6, 4, 5, 5, 3, 3, 4, 5, 4, 4, 7, 3, 5, 3] 
2.6.5 :028 > array.my_any?(Numeric)
 => false 
2.6.5 :029 > array.any?(Numeric)
 => true 
2.6.5 :030 > 
```

2020-10-22 17:59 UTC, maelfosso commented on enumerable_methods.rb
> +    elsif argument.class && !argument.nil == Regexp
After fixing that bug the result is still not good

2020-10-22 17:59 UTC, maelfosso commented on enumerable_methods.rb
> +  end
```rb
2.6.5 :032 > words
 => ["dog", "door", "rod", "blade"] 
2.6.5 :033 > words.my_any?(Integer)
 => true 
2.6.5 :034 > words.any?(Integer)
 => false 
2.6.5 :035 > 
```

2020-10-22 17:59 UTC, maelfosso commented on enumerable_methods.rb
> +  end
```rb
2.6.5 :037 > words
 => ["dog", "door", "rod", "blade"] 
2.6.5 :038 > words.my_any?(/d/)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):38
        1: from enumerable_methods.rb:62:in `my_any?'
NoMethodError (undefined method `nil' for /d/:Regexp)
Did you mean?  nil?
2.6.5 :039 > words.any?(/d/)
 => true 
2.6.5 :040 > words.my_any?(/z/)
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):40
        1: from enumerable_methods.rb:62:in `my_any?'
NoMethodError (undefined method `nil' for /z/:Regexp)
Did you mean?  nil?
2.6.5 :041 > words.any?(/z/)
 => false 
2.6.5 :042 >
```

2020-10-22 17:59 UTC, maelfosso commented on enumerable_methods.rb
> +    elsif argument.class && !argument.nil == Regexp
It's `nil?` not `nil`

Even after fixing that bugs, `#my_any?` is not working like expected.

2020-10-22 17:59 UTC, maelfosso commented on enumerable_methods.rb
> +end
```rb
2.6.5 :049 > range = Range.new(5, 50)
2.6.5 :050 > range.my_inject(4) { |prod, n| prod * n }
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):50
        1: from enumerable_methods.rb:99:in `my_inject'
NoMethodError (undefined method `is_a' for 4:Integer)
Did you mean?  is_a?
2.6.5 :051 > range.inject(4) { |prod, n| prod * n }
 => 5069015533618896340602101361010794807396273594826752000000000000 
2.6.5 :052 > 
```

2020-10-22 17:59 UTC, maelfosso commented on enumerable_methods.rb
> +    if (!argument.nil? && sym.nil?) && (argument.is_a?(Symbol) || argument.is_a(String))
It's not `is_a` is `is_a?`

2020-10-22 17:59 UTC, maelfosso commented on enumerable_methods.rb
> +    if !sym.nil? && !block_given
It's not `block_given` is `block_given?`

2020-10-22 21:21 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [x] check below 👇 

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-10-22 21:21 UTC, Spayco commented on enumerable_methods.rb
> +
- [ ] 🛑 do not disable rubocop - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))

  remove this line and fix the issues please.

2020-10-23 00:33 UTC, acushlakoncept approved these changes
# Status: PROJECT APPROVED  🎉 🚀

### Hello Team! 👋 

Great Job, well done on your progress thus far. 

All tests passed successfully! 👍 

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next project.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-10-23 00:53 UTC, merged